apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: colleague-feedback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ilyaponomarenko/colleague-feedback-backend:main-v1
        ports:
        - containerPort: 4500
        envFrom:
        - configMapRef:
            name: backend-config
      restartPolicy: Always
