apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: colleague-feedback
spec:
  selector:
    app: colleague-feedback-backend
  ports:
    - protocol: TCP
      port: 4500
      targetPort: 4500
      nodePort: 30080
  type: NodePort