apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-server-backend
  namespace: colleague-feedback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-server-backend
  template:
    metadata:
      labels:
        app: ldap-server-backend
    spec:
      containers:
      - name: ldap-server-backend
        image: ilyaponomarenko/colleague-feedback-backend:ldap-server-v3
        ports:
        - containerPort: 5600
        env:
        - name: LDAP_URL
          value: ldap://ldap-service.colleague-feedback.svc.cluster.local:389
        envFrom:
        - configMapRef:
            name: backend-config

