apiVersion: v1
kind: Service
metadata:
  name: colleague-feedback-backend
  namespace: colleague-feedback
spec:
  selector:
    app: colleague-feedback-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4500
  type: LoadBalancer
